theme = "coffee"

# The URL the site will be built for
base_url = "https://mapleblanc46.github.io/"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "docs"

# The site title and description; used in feeds by default.
title = "æ¤›ã®ãƒ–ãƒ­ã‚°(ä»®ç§°)"
description = "è¦‹ãŸãªï¼Ÿé‡‘ã‚’æ‰•ãˆã€ã‚‚ã—ãã¯è¶…ã‹ãã‚„å§«ï¼ã‚’è¦³ã‚"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# RSS/Atom feeds
generate_feeds = true
# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["rss.xml"]

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
    {name = "tags", feed = true},
]

[markdown.highlighting]
# The syntax highlighting theme to use in light mode
light_theme = "github-light"
# The syntax highlighting theme to use in dark mode
dark_theme = "github-dark"

[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the RFC3339 datetime of the page in the search index
include_date = true
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = true

[slugify]
# Various slugification strategies, see below for details
# Defaults to everything being a slug
paths = "off"
taxonomies = "off"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = true

[extra.coffee] #<- CAUTION: You have to be [extra.coffee], not [extra].
# default value: 'en'
lang = "ja"
# default value: 'blog'
keyword = "blog"
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/favicon.svg'
# A shortcut icon has to be a SVG image.
icon = "https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/favicon.svg"
# default value: ''
twitter_site = ""
# default value: '@yuki_osada0808'
twitter_creator = "@yuki_osada0808"
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/coffee.webp'
meta_image = "https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/coffee.webp"
# default value: 'coffee theme'
meta_image_alt = "coffee theme"
# default value: '512'
meta_image_width = "512"
# default value: '512'
meta_image_height = "512"

# default value is below
about = """
æ¤›ã‚’åä¹—ã£ã¦ã„ã¾ã™ã€‚
<br>
TRPGã€ã‚²ãƒ¼ãƒ å…¨èˆ¬ã€ã‚¦ãƒå¨˜ã€æƒ…å ±æŠ€è¡“ãŒå¥½ãã€‚
<br>
X(æ—§Twitter)ï¼š@maple_blanc
"""
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/coffee.webp'
about_image = "https://raw.githubusercontent.com/Myxogastria0808/coffee/heads/main/static/coffee.webp"
# default value: 'coffee theme'
about_image_alt = "coffee theme"
# default value: '512'
about_image_width = "512"
# default value: '512'
about_image_height = "512"
